export const SET_PASSWORD = "SET_PASSWORD"
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL"
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_STATE = 'RESET_PASSWORD_STATE'
